server:
  port: 9090
#   Root path of or entry from here only
  servlet:
    context-path: "/api/v1"
spring:
  output:
    ansi:
      enabled: always
#      spring boot unique id or spring boot application name
  application:
    name: SPRING-BOOT-CURD-REDIS
  datasource:
    url: jdbc:mysql://localhost:3306/productDB
    username: root
    password: root
#    Hibernates connection which show database operations and update to any changes
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernates:
        show_sql: true
        format_sql: true
# Which to void non value inside the properties in any class
  jackson:
    default-property-inclusion: NON_NULL
# cache configuration
  cache:
    type: redis
    redis:
      cache-null-values: true
#  Redis configuration here
  redis:
    host: localhost
    port: 6379